import { Inter, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import PlanProvider from "./context/PlanContext";

const inter = Inter({
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased scroll-smooth`}
    >
      <body className="min-h-full flex flex-col">
        
        <PlanProvider>
          <Navbar/>
          {children}
        </PlanProvider>
        
      </body>
    </html>
  );
}
